language: go
sudo: false
services:
  - docker
matrix:
  include:
    - go: 1.7
    - go: 1.8
    - go: 1.x
    - go: master
  allow_failures:
    - go: master

  before_install:
   - go get github.com/tools/godep

  install:
    - godep restore
    
  script: 
    - go vet .
    - go test
    - go build
    - ls -al

script: 
  - docker build -t gmemstr/pogo .
  - docker run -d --rm --name pogo  -p 3000:3000 gmemstr/pogo
  - sleep 10
  - docker ps -a | grep gmemstr/pogo